name: llm_ai_eo
channels:
    - defaults
    - conda-forge
dependencies:
    - pip:
      - --pre -f https://mlc.ai/wheels mlc-ai-nightly
      - --pre -f https://mlc.ai/wheels mlc-chat-nightly
      - llm
      - llm-mlc
      - llm-sentence-transformers
    - conda-forge::git-lfs
    - jupyter
    - pandas
    - pip
    - python
