name: llm_ai_eo
channels:
    - defaults
    - conda-forge
dependencies:
    - pip:
      - --pre -f https://mlc.ai/wheels mlc-ai-nightly
      - --pre -f https://mlc.ai/wheels mlc-chat-nightly
      - llm
      - llm-mlc
      - llm-sentence-transformers
      - thisnotthat
    - bokeh
    - colorcet
    - conda-forge::git-lfs
    - conda-forge::spacy
    - conda-forge::umap-learn
    - datashader
    - holoviews
    - ipykernel
    - jupyter
    - matplotlib
    - pandas
    - pip
    - python
    - scikit-image
